version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: fxdeals
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: P@ssw0rd
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      DATASOURCE_URL: jdbc:postgresql://db:5432/fxdeals
      DATASOURCE_USERNAME: sa
      DATASOURCE_PASSWORD: P@ssw0rd
      TIME_ZONE: GMT+3
